### ISSUE TITLE
can this model be used for image classification tasks?

### ISSUE THREAD

**Issue by whj510** [muditbhargava66/PyxLSTM#19]
like training the times series data, then inference the classification result.

**Comment by muditbhargava66** [comment]
For image classification and vision-based application, i like to share a relevant paper:
  - **Paper**: https://arxiv.org/abs/2406.04303
  - **Codebase**: https://github.com/nx-ai/vision-lstm

I'm currently short on time due to some prior commitments, but you are welcome to share any relevant PR based on your experiments.

**Comment by whj510** [comment]
ok, thank you!

**Comment by whj510** [comment]
> For image classification and vision-based application, i like to share a relevant paper:
>   - **Paper**: https://arxiv.org/abs/2406.04303
>   - **Codebase**: https://github.com/nx-ai/vision-lstm
> 
> I'm currently short on time due to some prior commitments, but you are welcome to share any relevant PR based on your experiments.

ok,thank you!

**Comment by MarilynWuu** [comment]
So is this model not applicable to feature processing of images?I have two models and would like to use this model for a second stage model to further process the features obtained from the first model.
